name:                networked-ipd
version:             0.1.0.0
github:              "githubuser/networked-ipd"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/networked-ipd#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- configurator
- containers
- bytestring
- hspec
- http-client
- mtl
- network
- process
- random
- servant-client
- servant-server
- stm
- streamly
- text
- warp
- websockets

library:
  source-dirs: src

executables:
  server-exe:
    main: Server-Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - networked-ipd
  client-exe:
    main: Client-Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - networked-ipd

tests:
  networked-ipd-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - networked-ipd
